name: Deploy on Push to k8s-dev-deploy

on:
  push:
    branches:
      - k8s-dev-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: ssh ubuntu@15.207.24.98 'bash -s' < /home/ubuntu/deploy.sh
