name: CI
on:
  push:
    branches: [ k8s-dev-deploy ]
  pull_request:
    branches: [ k8s-dev-deploy ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/k8s-dev-deploy'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: bash /home/ubuntu/deploy.sh

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu
          remote_host: 15.207.24.98
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
