name: Manual Deployment

on:
  push:
    branches:
      - k8s-dev-deploy
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        default: 'production'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy application
      run: |
        ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@15.207.24.98 "bash -s" < deploy.sh
