name: CI
on:
 push:
  branches: [k8s-dev-deploy]
 pull_request:
  branches: [k8s-dev-deploy]
  
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/k8s-dev-deploy'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu
          remote_host: 15.207.24.98
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: List remote directory contents
        run: ssh -o StrictHostKeyChecking=no -i ${{secrets.SSH_PRIVATE_KEY}} ubuntu@15.207.24.98 'ls -al /home/ubuntu'
      - name: Run deploy.sh
        run: ssh -o StrictHostKeyChecking=no -i ${{secrets.SSH_PRIVATE_KEY}} ubuntu@15.207.24.98 'bash /home/ubuntu/deploy.sh'
